import 'package:youtube_explode_dart/youtube_explode_dart.dart';

class YouTubeService {
  YouTubeService() : _yt = YoutubeExplode();

  final YoutubeExplode _yt;

  Future<String> fetchTranscript(String url) async {
    final videoId = VideoId.parseVideoId(url);
    if (videoId == null) {
      throw YouTubeServiceException('Link YouTube không hợp lệ.');
    }

    try {
      final manifest = await _yt.videos.closedCaptions.getManifest(videoId);
      if (manifest.tracks.isEmpty) {
        throw YouTubeServiceException(
          'Video này không có phụ đề. Hãy upload file script .txt.',
        );
      }

      ClosedCaptionTrackInfo track;
      final englishTracks = manifest.getByLanguage('en', autoGenerated: true);
      if (englishTracks.isNotEmpty) {
        track = englishTracks.first;
      } else {
        track = manifest.tracks.first;
      }

      final captions = await _yt.videos.closedCaptions.get(track);
      final buffer = StringBuffer();
      for (final caption in captions.captions) {
        buffer.writeln(caption.text);
      }

      final transcript = buffer.toString().trim();
      if (transcript.isEmpty) {
        throw YouTubeServiceException('Phụ đề video trống.');
      }

      return transcript;
    } on YouTubeServiceException {
      rethrow;
    } on Exception catch (error) {
      throw YouTubeServiceException(
        'Không thể tải phụ đề: ${error.toString()}',
      );
    }
  }

  void dispose() {
    _yt.close();
  }
}

class YouTubeServiceException implements Exception {
  YouTubeServiceException(this.message);
  final String message;

  @override
  String toString() => message;
}
